In [ ]:
# !pip install tensorboardX
# !pip install jupyter-tensorboard
# !pip install tensorflow
# !pip install keras
# !pip install h5py
# !python -m pip install --upgrade tensorflow

In [6]:
# 1. 임포트 하자
import tensorflow as tf

# 행과 열을 만들자
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[2],[2]])

res = tf.matmul(matrix1, matrix2)

print(res, '\n')

tf.constant([1, 2, 3, 4, 5, 6])

x = tf.constant(([1,2,3,4]), shape=(2,2))
res02 = tf.math.multiply(x, x)
print(res02, '\n')

hap = tf.add(x, x)
print(hap, '\n')

tf.Tensor([[12]], shape=(1, 1), dtype=int32) 

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32) 



In [39]:
# 2. 행렬 연산을 구현해보자 
input01 = tf.constant([[3.0]])
input02 = tf.constant([[2.0]])
input03 = tf.constant([[5.0]])

hap = tf.add(input02, input03)
res = tf.multiply(input01, hap)
print(hap, '\n')
print(res, '\n')

res02 = tf.multiply(input01, tf.add(input02, input03))
print(res02, '\n')

tf.Tensor([[7.]], shape=(1, 1), dtype=float32) 

tf.Tensor([[21.]], shape=(1, 1), dtype=float32) 

tf.Tensor([[21.]], shape=(1, 1), dtype=float32) 



In [41]:
# 3. 즉시 기본 실행 : 메소드가 호출되는 시점이 가장 먼저 실행
print(tf.executing_eagerly(), '\n')

x = [[2]]
m = tf.matmul(x, x)

print('hello {}'.format(m))

True 

hello [[4]]


In [42]:
# 4. 반환 작업 : 어레이 객체를 리턴받는 것
a = tf.constant([[1,2],[3,4]])

print(a, '\n')
print(type(a), '\n')
print(a.shape, '\n')
print(a.dtype, type(a.dtype), '\n')
print(a.numpy(), '\n')
print(a.numpy().dtype, type(a.numpy()))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

<class 'tensorflow.python.framework.ops.EagerTensor'> 

(2, 2) 

<dtype: 'int32'> <class 'tensorflow.python.framework.dtypes.DType'> 

[[1 2]
 [3 4]] 

int32 <class 'numpy.ndarray'>


In [43]:
# 5. 브로드캐스팅(Broadcasting) 지원
b = tf.add(a, 1)
print(b, '\n')

# 6. 연산자 오버로딩 지원
print(a*b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [44]:
# 7. numpy 지원
import numpy as np

res = np.multiply(a,b)
print(res, type(res))

[[ 2  6]
 [12 20]] <class 'numpy.ndarray'>


In [45]:
# 8. Variable
name = tf.Variable('홍길동', tf.string)
kor = tf.Variable(100, tf.int32)
eng = tf.Variable(90, tf.int32)
tot = kor + eng

print(name.numpy(), '\n')
print(tot.numpy(), '\n')

name02 = tf.Variable(['홍길동'], tf.string)
name02.numpy()

b'\xed\x99\x8d\xea\xb8\xb8\xeb\x8f\x99' 

190 



array([b'\xed\x99\x8d\xea\xb8\xb8\xeb\x8f\x99'], dtype=object)

In [46]:
a = tf.Variable([3, 12345, 2.987976], tf.float32)
b = tf.Variable([1,2,3,4,5], tf.float32)
c = tf.Variable([12.3-4.85j, 7.5-6.12j], tf.complex64)

print(a, b, c, '\n')
print(a.numpy(), '\n')
print(b.numpy(), '\n')
print(c.numpy())

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([3.000000e+00, 1.234500e+04, 2.987976e+00], dtype=float32)> <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5])> <tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.12j])> 

[3.000000e+00 1.234500e+04 2.987976e+00] 

[1 2 3 4 5] 

[12.3-4.85j  7.5-6.12j]


In [47]:
# 9. tensor 차원을 리턴 받자  tf.zeros(), tf.rank()
# 배치 * 높이 * 너비 * 색상

my_img = tf.zeros([10, 299, 299, 3])
res = tf.rank(my_img)

print(my_img, '\n')
print(type(my_img), '\n')
print(res)

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
 

In [48]:
# 10. 요소를 리턴
my_v = tf.Variable([1,2,3,4])
my_s = my_v[2]

print(my_s)

tf.Tensor(3, shape=(), dtype=int32)


In [61]:
# 11. tf의 객체를 Variable로 연동해보자
my_val = tf.Variable(tf.zeros(2,2,3))  # 변수
print(my_val.numpy())

[0. 0.]


In [62]:
# 11. tf의 객체를 Variable로 연동해보자
my_val = tf.constant(tf.zeros(2,2,3))  # 상수
print(my_val.numpy())

[0. 0.]


In [51]:
# 12. 변수 자동 변환
v = tf.Variable(0.0)
v.numpy()

w = v+1  # w는 v값 기준으로 계산되는 tf.Tensor, 변수가 수식으로 사용하게 되면 tf.Tensor로 변환
w

v = tf.Variable(0.0)
v.assign_add(1)

print(v, '\n')
print(v.read_value())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0> 

tf.Tensor(1.0, shape=(), dtype=float32)


## 텐서 = 스칼라 또는 벡터 또는 매트릭스

In [53]:
import tensorflow as tf
# 3*2행의 float32값을 이용해서 값을 구현해보자
'''
1  2
3  4
5  6
'''
A = tf.Variable([[1,2],[3,4],[5,6]], dtype = tf.float32)
print(A.numpy(), '\n')

# 전체 값을 -로 변경해보자
A.assign([[-1,-2], [-3,-4], [-5,-6]])
print(A.numpy(), '\n')

# 3*2행의 값을 모두 0으로 초기화. float32
A = tf.Variable(tf.zeros([3,2]), dtype=tf.float32)
print(A.numpy, '\n')

# 3*2 행의 값 요소모두를 평균은 0, 표준편차 0.1의 정규난수로 초기화를 시켜보자
# tf.random.normal()
A = tf.Variable(tf.random.normal([3,2], mean=0.0, stddev=0.1, dtype=tf.dtypes.float32))
print(A.numpy, '\n')

# 3*2 행의 값 요소모두를 -1 ~ 3 까지의 범위의 균일값을 난수로 초기화 시켜라
A = tf.Variable(tf.random.uniform([3,2], minval=-1, maxval=3, dtype=tf.dtypes.float32))
print(A.numpy)

[[1. 2.]
 [3. 4.]
 [5. 6.]] 

[[-1. -2.]
 [-3. -4.]
 [-5. -6.]] 

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>> 

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.01617927, -0.02819046],
       [-0.15087171, -0.0390345 ],
       [-0.07301226,  0.03693333]], dtype=float32)>> 

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 2.7738037 ,  2.1032095 ],
       [ 1.0916338 , -0.57768965],
       [ 1.3006043 ,  2.74863   ]], dtype=float32)>>


In [54]:
# 13. f(x) 표현하는 연산 시스템
# log(x), exp(x), sin(x), cos(x), sigmoid(x), tanh(x) 등

A = tf.constant([1,2,3], tf.float32)
B = tf.math.log(A)
print(B.numpy(), '\n')

B = tf.math.sigmoid(A)
print(B.numpy(), '\n')

B = tf.math.tanh(A)
print(B.numpy())

[0.        0.6931472 1.0986123] 

[0.7310586  0.8807971  0.95257413] 

[0.7615942 0.9640276 0.9950547]


In [ ]:
14. softmax : 로지스틱 함수를 다차원으로 만든것
다항 로지스틱 회귀로 출력에 대한 확률분포 네트워크 출력을 하는 정규화
신경망의 활성화 함수로 자주 사용한다.
z = K로 실수값을 벡터로 받아서 입력 숫자에 지수에 비례하는 K개의 확률분포 정규화 시킨것

tf.nn.softmax(logits, axis, name)
softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

tf.nn.softmax(x)
입력 인수 x : 텐서, 정수 상수 텐서, 변수 상수
출력 값 : 1. x의 각 요소마다 exp()을 계산해서 A에 할당
          2. A의 요소를 모두 더해서 임의 변수 a에 넣는다
          3. A의 요소를 a로 나누어서 출력 텐서를 한다
          4. 출력 텐서 각 요소의 값은 확률은 나타낸다.

In [55]:
A = tf.constant([1,2,3], tf.float32)
B = tf.nn.softmax(A)
print(B.numpy(), '\n')   # 확률 분포

B = tf.reduce_sum(A)
print(B.numpy())

[0.09003057 0.24472848 0.66524094] 

6.0


In [57]:
# 15. 사용자 오퍼레이션(노드) 만드는 방법
'''
@tf.function
def 함수명():
    연산
    return
'''

# (a+b)*c  - myOP(a,b,c)
@tf.function
def myOP(a,b,c):
    t = tf.math.add(a,b)
    return tf.math.multiply(t,c)

A = tf.constant([1,2], tf.float32)
B = tf.constant([3,4], tf.float32)
C = tf.constant([5,6], tf.float32)
D = myOP(A,B,C)
print(D, type(D), '\n')
print(D.numpy())

tf.Tensor([20. 36.], shape=(2,), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'> 

[20. 36.]


In [69]:
# 16. 사용자 자료형 만들기
# tf.Module를 상속받아 구현한다
# tf.Module 인스턴스는 Variable을 포함해서 다른 모듈들을 탐색할 수 있다.
# trainable_variables = 훈련가능한 변수를 리턴

class MyModuleOne(tf.Module):
    def __init__(self):
        self.VO = tf.Variable(1.0)
        self.VS = [tf.Variable(x) for x in range(10)]
        
class MyOtherModule(tf.Module):
    def __init__(self):
        self.m = MyModuleOne()
        self.v = tf.Variable(10.0)
        
m = MyOtherModule()
print(len(m.variables), '\n')
print(m.variables, '\n')
print(m.m, '\n')  # 11은 m.m에서 다른값은 m.v에서
print(m.v, '\n')

12 

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>) 


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0> 



In [75]:
# 17. 케라스
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

model

In [82]:
# 18. 순차모델을 만들어보자
import tensorflow as tf

model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(100, name='Layer_0', input_shape=(1000,)),
        tf.keras.layers.Dense(10, name='Layer_1'),
        tf.keras.layers.Dense(1, name='Layer_2'),
    ]
)

model.summary()
print(type(model.layers[0]), '\n')
print(model.layers[0].name, '\n')

d = {k.name : i for i, k in enumerate(model.layers)}
print(d, '\n')
print(d['Layer_1'], '\n')

layer_name = [k.name for k in model.layers]
print(layer_name)

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Layer_0 (Dense)              (None, 100)               100100    
_________________________________________________________________
Layer_1 (Dense)              (None, 10)                1010      
_________________________________________________________________
Layer_2 (Dense)              (None, 1)                 11        
Total params: 101,121
Trainable params: 101,121
Non-trainable params: 0
_________________________________________________________________
<class 'tensorflow.python.keras.layers.core.Dense'> 

Layer_0 

{'Layer_0': 0, 'Layer_1': 1, 'Layer_2': 2} 

1 

['Layer_0', 'Layer_1', 'Layer_2']


In [ ]:
심층 신경망은 학습한 모든 변환을 수치 데이터 텐서에 적용하는 텐서 연산을 사용한다.
  ex) 텐서 덧셈, 텐서 곱셈
    
tf.keras.layers.Dense(1, name='Layer_2')  -> 신경망을 만들었다. 층을 설정했다.

데이터 -> 학습 구조 모델링 -> 학습 수행 -> 평가

In [87]:
# 19. 간단한 공식을 이용해서 값을 전달한 후 평가로 예측 값을 구현해보자
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

# y = ax + b
# 5 = a2 + b3 = a1 + b7 = a*3 + b

# 1단계) 데이터
x = np.array([1,2,3,4,5])
y = x*2 + 1
print(x)
print(y, '\n')


# 2단계) 학습 구조 모델링
model = Sequential()  # 레이어를 층층이 쌓아주는 메소드
model.add(Dense(1, input_shape=(1,)))
model.compile('SGD', 'mse')
# SGD(Stochastic Gradient Descent) : 확률적 경사 하강법
# mse(Mean Squered Error : 평균 제곱 오차)


# 3단계) 학습 수행 : 몇 번을 어떻게 할꺼야?
model.fit(x, y, epochs=1000, verbose=0)  
# epochs : 샘플데이터로 몇 번을 수행할건지


# 4단계) 평가
print('y :', y, ', predict :', model.predict(x).flatten())

[1 2 3 4 5]
[ 3  5  7  9 11] 

y : [ 3  5  7  9 11] , predict : [ 2.984122   4.9902043  6.996287   9.00237   11.008452 ]


In [90]:
# 20. tf.GradientTape API : 텐서플로는 자동 미분하는 API를 제공한다
# context 안에 실행된 모든 연산을 tape에 기록한다.
# 후진방식 자동미분을 사용해서 tape에 기록된 연산 결과를 계산한다.
# 기울기를 구하는 클래스 : 정밀한 예측 모델을 만들려면 적당히 선택한 매개 변수에서 
# 예상한 값과 실제 결과를 비교해서 가능한 차이가 적게 매개변수를 조정하게 된다.

x = tf.ones((2,2))

with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)
    
dz_dx = t.gradient(z,x)  # 입력텐서 x에 대한 z값
print(dz_dx, '\n')

for i in [0,1]:
    for j in [0,1]:
#         assert dz_dx[i][j] == 8.0
        dz_dx[i][j].numpy() == 8.0
        print(dz_dx[i][j])

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32) 

tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
