!jupyter nbconvert --to script day01.ipynb -> py로 변환하는 명령어

1. 기본정보(버전확인, 데이터 형식, 목록, 형변환, python list와 numpy.ndarray의 차이점)
2. 표시설정(numpy.ndarray 설정값, 배열의 초기화 및 생성 _행렬만들기, 난수 배열값 채우기, 대각선)
3. 배열의 행, 열, 추출, 추가, 삭제, 결합, 분할
4. 조건처리
5. 결측값 처리
6. 정렬
7. 파일의 입출력
8. 다른 형식으로 값 변환
9. 이미지 처리

배열의 초기화 및 생성 행렬만들기

1. 행과 열의 수를 지정해서 생성 = shape 형식 dtype 인수로 지정
    numpy.zeros() - 0으로 채움
    numpy.ones() - 1로 채움
    numpy.full() - 임의의 값으로 초기화
    
2. 기존의 배열 형식으로 값을 대입해서 생성
    numpy.zeros_like() - 0으로 채움
    numpy.ones_like() - 1으로 채움
    numpy.full_like() - 임의의 값으로 초기화
    
3. 기존 배열의 전체 요소 값을 원하는 값으로 대체해서 생성

In [1]:
# 1. 행과 열의 수를 지정해서 생성 = shape 형식 dtype 인수로 지정
import numpy as np

# 0으로 채움
print(np.zeros(2), '\n')  # 1차원
print(np.zeros((2,3)), '\n')  # 2차원
print(np.zeros([2,2,3]), '\n')  # 3차원
print(np.zeros([2,2,3], dtype = np.int), '\n')  # 3차원 정수
print(np.zeros([2,2,3], dtype = np.float))  # 3차원 실수
print("=================================", '\n')

# 1로 채움
print(np.ones([2,2,3], dtype = np.int), '\n')  # 3차원 정수
print(np.ones([2,2,3], dtype = np.float))  # 3차원 실수
print("=================================", '\n')

# 임의의 값으로 초기화  numpy.full(shape, fill_value)
print(np.full(3, 100), '\n')
print(np.full((2,3),np.pi), '\n')
print(np.full((2,3),np.pi, dtype=np.int), '\n')

[0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]] 

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

[100 100 100] 

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]] 

[[3 3 3]
 [3 3 3]] 



In [2]:
# 2. 기존의 배열 형식으로 값을 대입해서 생성

a_int = np.arange(6).reshape(2,3)
print(a_int, '\n')

a_float = np.arange(6).reshape((2,3)) / 10
print(a_float, '\n')

# 0으로 채움
print(np.zeros_like(a_int), '\n')  # 기존 배열에 값을 0으로 대입 후 생성
print(np.zeros_like(a_int, dtype=float))  # 기존 배열에 값을 0으로 대입 후 생성
print("=================================", '\n')

# 1로 채움
print(np.ones_like(a_int), '\n')  # 기존 배열에 값을 1로 대입 후 생성
print(np.ones_like(a_int, dtype=float))  # 기존 배열에 값을 1로 대입 후 생성
print("=================================", '\n')

# 임의의 값으로 초기화  numpy.full(shape, fill_value)
print(np.full_like(a_float, 0.12345))
print("=================================", '\n')

# ex) 지정된 배열값을 변경해보자
a = np.arange(6).reshape(2,3)
print(a, '\n')

b = np.zeros_like(a)
print(b, '\n')

# 슬라이스를 이용해서 값을 변경해보자
a[:,:] = 0  # 행과 열
print(a, '\n')

a[:] = 1  # 전체
print(a, '\n')

a[:] = 1.0  # 타입이 정수인 객체라서 타입을 변경해줘야한다.
print(a, '\n')

a = a.astype(np.float)  # float타입으로 변경
a[:] = 1.0
print(a, '\n')

a = a.astype(np.str)  # 문자열로 변경
a[:] = 1.0
print(a, '\n')

[[0 1 2]
 [3 4 5]] 

[[0.  0.1 0.2]
 [0.3 0.4 0.5]] 

[[0 0 0]
 [0 0 0]] 

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1]
 [1 1 1]] 

[[1. 1. 1.]
 [1. 1. 1.]]

[[0.12345 0.12345 0.12345]
 [0.12345 0.12345 0.12345]]

[[0 1 2]
 [3 4 5]] 

[[0 0 0]
 [0 0 0]] 

[[0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]] 

[[1 1 1]
 [1 1 1]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[['1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0']] 



난수 배열값 채우기, 대각선   numpy.random
1. 균일 분포 난수 생성
    numpy.random.rand() : 0.0 이상 1.0 미만
    numpy.random.random_sample() : 0.0 이상 1.0 미만
    numpy.random.randint() : 정수 난수
    
2. 정규 분포 난수 생성
    randn() : 평균 0, 분산 1 (표준편차 1)
    normal() : 임의의 평균, 표준편차
    * 표준편차, 상관계수가 같아도 꼭 데이터의 분포가 같은 것은 아님
    
3. 이항 분포 난수 생성    X~B(n,p) = 확률변수 ~(횟수, 확률) - 사건이 발생했을 때 일어날 확률이 p이고 n번 반복한 것
    binomial()

4. 베타 분포 난수 생성
    beta()
    
5. 감마 분포 난수 생성
    gama()
    
6. 카이 제곱 분포 난수 생성
    chisquare()


In [3]:
# 1. 균일 분포
# 일차원 3개의 난수
m_rand = np.random.rand(3)
print(m_rand, '\n')

# 3차원 2,3개의 난수
m_rand = np.random.rand(2,3)
print(m_rand, '\n')

# 삼차원 2,2,3,개의 난수
m_rand = np.random.rand(2,2,3)
print(m_rand, '\n')

# 연산할 경우 a~b 까지 난수 발생하고 싶다.
# (b-a) * np.random.rand() + a


[0.83579488 0.50332446 0.49864722] 

[[0.50341841 0.740779   0.42160464]
 [0.00513151 0.61849877 0.87120608]] 

[[[0.22999661 0.51697501 0.04160836]
  [0.79348183 0.38723867 0.48949532]]

 [[0.01051893 0.65490767 0.46765237]
  [0.02773371 0.97201139 0.73247332]]] 



In [6]:
# 1. 균일 분포
# 일차원 3개의 난수
m_rand = np.random.random_sample(3)
print(m_rand, '\n')

# 3차원 2,3개의 난수
m_rand = np.random.random_sample((2,3))
print(m_rand, '\n')

# 삼차원 2,2,3,개의 난수
m_rand = np.random.random_sample((2,2,3))
print(m_rand, '\n')

print(np.random.random_sample is np.random.rand)

[0.50769683 0.64066766 0.94316523] 

[[0.67228728 0.84612784 0.68451485]
 [0.03871185 0.91060896 0.30811353]] 

[[[0.40563651 0.15735489 0.6594316 ]
  [0.69752655 0.58354548 0.45115761]]

 [[0.36234673 0.02572605 0.98639393]
  [0.48162798 0.3273218  0.78872773]]] 

False


In [7]:
# 2. 정규 분포
# randint(최소값, 최대값, 형식, dtype)
# 4이상 10이하의 3*3 배열의 난수값을 가진 객체를 생성해보자
ar = np.random.randint(4,10,(3,3))
print(ar)

[[8 5 6]
 [8 5 5]
 [5 8 6]]


In [39]:
# 2. 정규 분포  random.normal( loc = 0.0., scale = 1.0, size = None)
# loc = 평균, scale = 정규 분포에 따른 난수
arr = np.random.normal(-2, 0.5, (3,3))
print(arr)

[[-2.29677774 -2.92291689 -2.29659877]
 [-1.75098338 -1.84669699 -1.52476848]
 [-1.87943888 -1.50257355 -2.62807488]]


값 채우기
1. 주어진 숫자를 간격으로 채우기(파이썬의 range()는 정수만 arange()는 정수 + 실수가능)
    arange(end, dtype) : 0 <= n < end 1증가
    arange(start, end, dtype) : start <= n < end 1증가
    arange(start, end, step, dtype) : start <=n < end step 증가
                              
2. 요소 수를 지정해서 채우기
    linspace(start, end, 분할개수, retstep, dtype, endpoint)
    
3. 역순으로 변환

4. 다차원으로 변환 채우기

In [8]:
# 2. 요소 수를 지정해서 채우기 linspace(start, end, 분할개수, retstep, dtype, endpoint)
print(np.linspace(0,10,3), '\n')  # 0 부터 10까지 3등분
print(np.linspace(0,10,4), '\n')
print(np.linspace(1,10,5), '\n')

print(np.linspace(10,0,5, dtype=int), '\n')
print(np.linspace(10,0,5, endpoint=False, dtype=int), '\n')  # endpoint=False 0(endpoint)를 포함하지 않고 5등분
print(np.linspace(10,0,5, endpoint=False, dtype=int, retstep=True))

[ 0.  5. 10.] 

[ 0.          3.33333333  6.66666667 10.        ] 

[ 1.    3.25  5.5   7.75 10.  ] 

[10  7  5  2  0] 

[10  8  6  4  2] 

(array([10,  8,  6,  4,  2]), -2.0)


In [12]:
# 3. 역순으로 변환  arange(), [::-1], flip()
# arange()
print(np.arange(3,10,2), '\n')
print(np.arange(10,3,-2), '\n')

# [::-1]
print(np.arange(3,10,2)[::-1], '\n')

# flip()
print(np.flip(np.arange(3,10,2)))

[3 5 7 9] 

[10  8  6  4] 

[9 7 5 3] 

[9 7 5 3]


In [9]:
# 4. 다차원으로 변환 채우기
# 2d 3d = 다차원배열로 등차 수열을 생성한다. reshape()
print(np.arange(12).reshape(3,4), '\n')
print(np.linspace(0,10,12, dtype=int).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


In [2]:
# 대각선  diag()  추출 : 다차원 배열의 배열을 대각선으로 추출해서 1차원으로 리턴, 생성 : 단위행렬
ar = np.arange(9).reshape(3,3)  # 정방 행렬
print(ar, '\n')

# ar의 대각선 값을 리턴해보자(추출)
res = np.diag(ar)
print(res, type(res), '\n')
res.flags.writeable = True  # 기본은 읽기 전용이라서 값을 수정할 수 없다. 그러나 true를 설정하면 값을 수정할 수 있다.

res[0] = 1000
print(res, '\n')
print(ar, '\n')

res = np.diag(ar).copy()  # 복사해서 또 다른 res라는 객체주소
print(res, type(res), '\n')
res[0]=9999
print(res, '\n')
print(ar, '\n')

res = np.diag(ar, k=1)  # 시작위치를 0이 아닌 1부터 시작. 정수는 오른쪽 위쪽
print(res, '\n')

res = np.diag(ar, k=2)  # 시작위치를 0이 아닌 2부터 시작. 정수는 오른쪽 위쪽
print(res, '\n')

res = np.diag(ar, k=-1)  # 시작위치를 0이 아닌 3부터 시작. 음수는 왼쪽의 아래
print(res, '\n')

res = np.diag(ar, k=-2)  # 시작위치를 0이 아닌 6부터 시작. 음수는 왼쪽의 아래
print(res, '\n')
print("==========================")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 4 8] <class 'numpy.ndarray'> 

[1000    4    8] 

[[1000    1    2]
 [   3    4    5]
 [   6    7    8]] 

[1000    4    8] <class 'numpy.ndarray'> 

[9999    4    8] 

[[1000    1    2]
 [   3    4    5]
 [   6    7    8]] 

[1 5] 

[2] 

[3 7] 

[6] 



In [7]:
# 대각선  diag()  추출 : 다차원 배열의 배열을 대각선으로 추출해서 1차원으로 리턴, 생성 : 단위행렬
ar = np.arange(12).reshape(3,4)  # 정방 행렬이 아닐 경우
print(ar, '\n')

# ar의 대각선 값을 리턴해보자(추출)
res = np.diag(ar)
print(res, '\n')

res = np.diag(ar, k=1)  # 시작위치를 0이 아닌 1부터 시작. 정수는 오른쪽 위쪽
print(res, '\n')

res = np.diag(ar, k=2)  # 시작위치를 0이 아닌 2부터 시작. 정수는 오른쪽 위쪽
print(res, '\n')

res = np.diag(ar, k=-1)  # 시작위치를 0이 아닌 3부터 시작. 음수는 왼쪽의 아래
print(res, '\n')

res = np.diag(ar, k=-2)  # 시작위치를 0이 아닌 6부터 시작. 음수는 왼쪽의 아래
print(res, '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  5 10] 

[ 1  6 11] 

[2 7] 

[4 9] 

[8] 



In [4]:
# np.diag를 이용해서 대각선으로 객체 생성(단위행렬 다차원x)
a = np.array([10,20,30,40,50,60])
print(a, '\n')
print(np.diag(a), '\n')
print(np.diag((10,20,30,40,50,60)), '\n')
print(np.diag((10,20,30,40,50,60), k=-2), '\n')
print("=====================")

# 대각선 전용함수 중 1로 채운다: np.identity(크기, 형식)
print(np.diag((1,1,1)), '\n')  # 값을 지정하면서 대각서 배열 객체 생성
print(np.identity(3,int))  # 대각선의 크기만 지정하면 1로 채운다

[10 20 30 40 50 60] 

[[10  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0 30  0  0  0]
 [ 0  0  0 40  0  0]
 [ 0  0  0  0 50  0]
 [ 0  0  0  0  0 60]] 

[[10  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0 30  0  0  0]
 [ 0  0  0 40  0  0]
 [ 0  0  0  0 50  0]
 [ 0  0  0  0  0 60]] 

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0]
 [ 0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0 60  0  0]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


대각선 전용함수 중 1로 채운다: np.identity(크기, 형식)
one - hot 전용함수(1-of-k) : 데이터셋이 있을 경우 하나만 1이고 나머지는 0으로 채우는 것
one - cold : 데이터셋이 있을 경우 하나만 0이고 나머지는 1로 채우는 것

텐서 플로 등의 기계학습에서 분류할 때 정답을 one - hot으로 표현한다.
 ex) (0~9) 필기한 숫자 = 10종류의 데이터셋 + MNIST을 적용 = 정답(레벨 2인 경우 one - hot은?
     [0,0,1,0,0,0,0,0,0,0]

In [8]:
# 단위행렬을 이용해서 one - hot을 해보자
# ex) 10*10의 행렬을 만들어 지정된 원본데이터를 대입시켜 one - hot를 리턴해보자
a= [1,4,2,6,5]
a_one_hot = np.identity(10)[a]
print(a, '\n')
print(a_one_hot, '\n')
print("===============================")

a= [2,2,0,1,0]
a_one_hot = np.identity(3)[a]
print(a, '\n')
print(a_one_hot, '\n')

[1, 4, 2, 6, 5] 

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]] 

[2, 2, 0, 1, 0] 

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]] 



In [9]:
ar = np.eye(3)
print(ar, '\n')

ar02 = np.eye(4, k=1, M=3)  # M은 열의 크기, k는 시작위치
print(ar02, '\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [11]:
# 배열의 행, 열, 추출(슬라이스), 추가(append, insert), 삭제(delete), 결합, 분할(split)

print(ar[1:2], '\n')
ar03 = np.arange(24).reshape(2,3,4)
print(ar03, '\n')
print(ar03[1,[True,False,True],::2], '\n')
print(ar03[0,1,2])


[[0. 1. 0.]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

[[12 14]
 [20 22]] 

6


In [13]:
# boolean으로 데이터 추출

a_1d = np.arange(4)
print(a_1d, '\n')
print(a_1d[[True,False,True,False]], '\n')
print(a_1d[np.array([True,False,True,False])], '\n')

a_2d = np.arange(12).reshape(3,4)
print(a_2d, '\n')
print(a_2d[[True, False, True]], '\n')  # 행

# 행은 전체 출력, 열은 index 1,3
print(a_2d[:,[False, True, False, True]], '\n')  # 행, 열을 리턴
print("-------------------------------------")

# 비교 연산자를 이용해서 데이터 추출. 7보다 큰 수만 출력해보자
print(a_2d > 7, '\n')
print(a_2d[a_2d > 7], '\n')

# 5보다 크고 10보다 작은 값들을 출력해보자
print(a_2d[(a_2d > 5) & (a_2d < 10) ], '\n')


[0 1 2 3] 

[0 2] 

[0 2] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 8  9 10 11]] 

[[ 1  3]
 [ 5  7]
 [ 9 11]] 

-------------------------------------
[[False False False False]
 [False False False False]
 [ True  True  True  True]] 

[ 8  9 10 11] 

[6 7 8 9] 



In [14]:
# 행, 열 추가(append)
a = np.arange(3)
print(a, '\n')

a_append = np.append(a,3)
print(a_append, '\n')
print(np.append(a, [3,4,5]), '\n')
print(np.append(a, np.arange(3,6)), '\n')

print(np.append([3,4,5], a), '\n')   # [3,4,5]에다가 a를 추가
print(np.append(np.arange(3,6), a), '\n')

[0 1 2] 

[0 1 2 3] 

[0 1 2 3 4 5] 

[0 1 2 3 4 5] 

[3 4 5 0 1 2] 

[3 4 5 0 1 2] 



In [18]:
# 2차원 추가
a_2d = np.arange(6).reshape(2,3)
print(a_2d, '\n')

print(np.append(a_2d,10), '\n')

a_2d_res = np.arange(6).reshape(2,3) * 5
print(a_2d_res, '\n')
print(np.append(a_2d, a_2d_res, axis=0), '\n')  # 세로로 연결 행 추가
print(np.append(a_2d, a_2d_res, axis=1), '\n')  # 가로로 연결 열 추가

[[0 1 2]
 [3 4 5]] 

[ 0  1  2  3  4  5 10] 

[[ 0  5 10]
 [15 20 25]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 0  5 10]
 [15 20 25]] 

[[ 0  1  2  0  5 10]
 [ 3  4  5 15 20 25]] 



* 행, 열 추가(insert) insert(arr, obj, value, axis)

1. 일차원 배열
    numpy.insert()

2. 이차원 배열의 행
    numpy.insert()
    numpy.vstack()
    
3. 이차원 배열의 열
    numpy.insert()
    numpy,hstack()

In [3]:
a = np.arange(3)
print(a, '\n')

a_insert = np.insert(a,2,100)  # 값, 인덱스위치, 추가할 값. index 위치를 정확히 명시해줘야함
print(a_insert, '\n')

a_insert = np.insert(a,2,[100,101,102])
print(a_insert)
print('------------------------------------', '\n')

# 2차원에 insert를 이용하여 데이터 추가
a = np.arange(12).reshape((3,4))
print(a, '\n')

a_res = np.insert(a, 2, 100, axis = 0)
print(a_res, '\n')

a_res = np.insert(a, 2, 100, axis = 1)
print(a_res, '\n')

data = np.arange(100,104)
print(data, '\n')

a_res = np.insert(a, 2, data, axis = 0)
print(a_res)
print('------------------------------------', '\n')


print(np.vstack((a,data)))

[0 1 2] 

[  0   1 100   2] 

[  0   1 100 101 102   2]
------------------------------------ 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[  0   1   2   3]
 [  4   5   6   7]
 [100 100 100 100]
 [  8   9  10  11]] 

[[  0   1 100   2   3]
 [  4   5 100   6   7]
 [  8   9 100  10  11]] 

[100 101 102 103] 

[[  0   1   2   3]
 [  4   5   6   7]
 [100 101 102 103]
 [  8   9  10  11]]
------------------------------------ 

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 101 102 103]]


In [9]:
# 삭제 delete (객체, 행, 열)
print(a, '\n')

print(np.delete(a,1), '\n')  # 해당 원소만 삭제
print(np.delete(a,(0,1,3)), '\n')  # 여러 원소 삭제 가능

print(np.delete(a, 0, axis=0), '\n')  # 행 삭제
print(np.delete(a, 0, axis=1), '\n')  # 열 삭제

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  2  3  4  5  6  7  8  9 10 11] 

[ 2  4  5  6  7  8  9 10 11] 

[[ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] 



In [10]:
# 결합 : [np.concatenate(), stack(),] / 2차원 block(), vstack(), hstack(), dstack()

a1 = np.ones((2,3), int)
print(a1, '\n')

a2 = np.full((2,3), 2)
print(a2, '\n')

print(np.concatenate([a1,a2],0), '\n')
print(np.concatenate([a1,a2],1), '\n')

print(np.block([a1,a2]), '\n')


[[1 1 1]
 [1 1 1]] 

[[2 2 2]
 [2 2 2]] 

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]] 

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]] 

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]] 



In [11]:
# 결합 : [np.concatenate(), stack(),] / 2차원 block(), vstack(), hstack(), dstack()

a1 = np.ones(3, int)
print(a1, '\n')

a2 = np.full(3, 2)
print(a2, '\n')

print(np.stack([a1,a2]), '\n')

[1 1 1] 

[2 2 2] 

[[1 1 1]
 [2 2 2]] 



In [12]:
# 분할 split(), array_split(), vsplit(), hsplit(), dsplit()
# 4*4 데이터를 채워서 2개로 분할
# split()
res = np.arange(16).reshape(4,4)
print(np.split(res,2), '\n')
print(np.split(res,2)[0], '\n')
print(np.split(res,2)[1], '\n')

a,b = np.split(res,2)
print(a, '\n')
print(b, '\n')

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [13]:
# 분할 split(), array_split(), vsplit(), hsplit(), dsplit()
# array_split()
res = np.arange(15).reshape(3,5)
print(np.array_split(res,2), '\n')

a,b = np.array_split(res,2)
print(a, '\n')
print(b)
print('-------------------------------', '\n')

# vsplit()
res = np.arange(16).reshape(4,4)
print(np.vsplit(res,2), '\n')

a,b = np.vsplit(res,2)
print(a, '\n')
print(b)
print('-------------------------------', '\n')

# hsplit()
res = np.arange(16).reshape(4,4)
print(np.hsplit(res,2), '\n')

a,b = np.hsplit(res,2)
print(a, '\n')
print(b)
print('-------------------------------', '\n')

# dsplit()
res = np.arange(24).reshape(2,3,4)
print(res, '\n')

print(np.dsplit(res,2))
print('-------------------------------', '\n')

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]])] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[10 11 12 13 14]]
------------------------------- 

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]
------------------------------- 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
------------------------------- 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
------------------------------- 



In [10]:
# 4. 조건처리  numpy.where(condition, [x,y])  & |
ar = np.arange(9).reshape(3,3)
print(ar, '\n')

# ar이 4보다 작으면, -1, 999로 채우자
r = np.where(ar < 4, -1, 999)
print(r, '\n')

r = np.where(ar < 4, True, False)
print(r, '\n')

r = np.where(ar < 4, ar*10, ar-10)  # 연산 가능
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ -1  -1  -1]
 [ -1 999 999]
 [999 999 999]] 

[[ True  True  True]
 [ True False False]
 [False False False]] 

[[ 0 10 20]
 [30 -6 -5]
 [-4 -3 -2]]


In [11]:
# ex) 6개의 순차 배열값을 만들고 3보다 작은 값들을 추출해서 튜플로 만들자
ar = np.arange(6)
print(np.where(ar < 3), '\n')
print(np.where(ar < 3)[0], '\n')
print(np.where(ar < 3)[0].tolist(), '\n')  # 차원으로 리턴
print(list(zip(*np.where(ar < 3))))  # 튜플로 리턴

(array([0, 1, 2], dtype=int64),) 

[0 1 2] 

[0, 1, 2] 

[(0,), (1,), (2,)]


In [30]:
# 5. 결측값 처리.  NaN 값을 처리하는 것. np.nan, np.nan_to_num(), np.isnan()
type(np.nan)
print(np.nan == np.nan, '\n')  # 결손값 간의 == 비교 연산시 False
print(np.isnan(np.nan), '\n')
print(float('nan'), np.math.nan, np.math.isnan(np.nan), '\n')

# np.genfromtxt  -> 복잡한 서식이 있는 파일을 로드 단, 결측값 처리
a = np.genfromtxt('C:\\Users\\USER\\MyPython\\sample.csv', delimiter = ',') 
print(a, '\n')
print(np.isnan(a), '\n')

r = np.nan_to_num(a)  # 결손시 데이터 전부 0으로 처리(float 값이 아닌거)
print(r, '\n')

r = np.nan_to_num(a, nan = -1)  # nan값만 -1로 처리
print(r, '\n')

a = np.genfromtxt('C:\\Users\\USER\\MyPython\\sample.csv', delimiter = ',') 
print(np.nanmean(a), '\n')  # NaN 값을 무시하고 평균을 구하는 함수

r = np.nan_to_num(a, nan = np.nanmean(a))
print(r, '\n')

r = np.nan_to_num(a, nan = np.nanmean(a)*10)
print(r)

False 

True 

nan nan True 

[[ 11.  12. 100.  nan]
 [ 21.  22.  23.  24.]
 [ 31.  82.  nan  34.]
 [ nan  42.  43.  44.]] 

[[False False False  True]
 [False False False False]
 [False False  True False]
 [ True False False False]] 

[[ 11.  12. 100.   0.]
 [ 21.  22.  23.  24.]
 [ 31.  82.   0.  34.]
 [  0.  42.  43.  44.]] 

[[ 11.  12. 100.  -1.]
 [ 21.  22.  23.  24.]
 [ 31.  82.  -1.  34.]
 [ -1.  42.  43.  44.]] 

37.61538461538461 

[[ 11.          12.         100.          37.61538462]
 [ 21.          22.          23.          24.        ]
 [ 31.          82.          37.61538462  34.        ]
 [ 37.61538462  42.          43.          44.        ]] 

[[ 11.          12.         100.         376.15384615]
 [ 21.          22.          23.          24.        ]
 [ 31.          82.         376.15384615  34.        ]
 [376.15384615  42.          43.          44.        ]]
