!jupyter nbconvert --to script day01.ipynb -> py로 변환하는 명령어

1. 기본정보(버전확인, 데이터 형식, 목록, 형변환, python list와 numpy.ndarray의 차이점)
2. 표시설정(numpy.ndarray 설정값, 배열의 초기화 및 생성 _행렬만들기, 난수 배열값 채우기, 대각선)
3. 배열의 행, 열, 추출, 추가, 삭제, 결합, 분할
4. 조건처리
5. 결측값 처리
6. 정렬 계산
7. 파일의 입출력, 8. 다른 형식으로 값 변환
9. 이미지 처리

In [6]:
import numpy as np

# 5. 결측값 처리.  NaN 값을 처리하는 것. np.nan, np.nan_to_num(), np.isnan()
# float('nan')
type(np.nan)
print(np.nan == np.nan, '\n')  # 결손값 간의 == 비교 연산시 False
print(np.isnan(np.nan), '\n')
print(float('nan'), np.math.nan, np.math.isnan(np.nan), '\n')

# np.genfromtxt  -> 복잡한 서식이 있는 파일을 로드 단, 결측값 처리
a = np.genfromtxt('C:\\Users\\USER\\MyPython\\sample.csv', delimiter = ',') 
print(a, '\n')

r = np.nan_to_num(a)  # 결손시 데이터 전부 0으로 처리(float 값이 아닌거)
print(r, '\n')

r = np.nan_to_num(a, nan = -1)  # nan값만 -1로 처리
print(r, '\n')

a = np.genfromtxt('C:\\Users\\USER\\MyPython\\sample.csv', delimiter = ',') 
print(np.nanmean(a), '\n')
r = np.nan_to_num(a, nan = np.nanmean(a))
print(r, '\n')

r = np.nan_to_num(a, nan = a*10)   # 적용되지 않는다
print(r)

False 

True 

nan nan True 

[[ 11.  12. 100.  nan]
 [ 21.  22.  23.  24.]
 [ 31.  82.  nan  34.]
 [ nan  42.  43.  44.]] 

[[ 11.  12. 100.   0.]
 [ 21.  22.  23.  24.]
 [ 31.  82.   0.  34.]
 [  0.  42.  43.  44.]] 

[[ 11.  12. 100.  -1.]
 [ 21.  22.  23.  24.]
 [ 31.  82.  -1.  34.]
 [ -1.  42.  43.  44.]] 

37.61538461538461 

[[ 11.          12.         100.          37.61538462]
 [ 21.          22.          23.          24.        ]
 [ 31.          82.          37.61538462  34.        ]
 [ 37.61538462  42.          43.          44.        ]] 

[[ 11.  12. 100.  nan]
 [ 21.  22.  23.  24.]
 [ 31.  82.  nan  34.]
 [ nan  42.  43.  44.]]


In [12]:
# np.isnan() -> 결손치, 결측값 NaN 여부를 판정하는 함수
a = np.genfromtxt('C:\\Users\\USER\\MyPython\\sample.csv', delimiter = ',')

print(a, '\n')

print(np.isnan(a), '\n')   # 결손치 값(nan)을 리턴

print(~np.isnan(a), '\n')   # 결손치 값이 아닌 값을 리턴

print(a[np.isnan(a)])  # 결손치 값만 출력

[[ 11.  12. 100.  nan]
 [ 21.  22.  23.  24.]
 [ 31.  82.  nan  34.]
 [ nan  42.  43.  44.]] 

[[False False False  True]
 [False False False False]
 [False False  True False]
 [ True False False False]] 

[[ True  True  True False]
 [ True  True  True  True]
 [ True  True False  True]
 [False  True  True  True]] 

[nan nan nan]


* ndarray.any() : True 값이 하나라도 있을 경우 사용
결손치 Nan이 있는 행을 삭제 할 경우 Numpy 배열 ndarray에 하나라도 True가 있을 경우 any() 메소드를 이용해서 삭제하게된다.

* ndarray.all()
모든 요소가 결측인 행만 리턴받으려면 all()을 사용

In [16]:
# ndarray.any()
# axis = 1 지정해서 각행에 하나라도 True의 유무를 판별해보자
print(np.isnan(a).any(axis=1))  

# ~를 사용하게되면 결측값이 하나도 없는 줄을 True로 리턴한다.
print(~np.isnan(a).any(axis=1))

# 결측값이 하나도 없는 행의 값을 리턴해보자
print(a[~np.isnan(a).any(axis=1), :])  # a[행, 열]
print(a[~np.isnan(a).any(axis=1)])  # a[행]

[ True  True  True False]
[False False False  True]
[[41. 42. 43. 44.]]
[[41. 42. 43. 44.]]


In [20]:
# axis = 0 지정해서 각행에 하나라도 True의 유무를 판별해보자
print(np.isnan(a).any(axis=0))  

# ~를 사용하게되면 결측값이 하나도 없는 줄을 True로 리턴한다.
print(~np.isnan(a).any(axis=0))

# 결측값이 하나도 없는 행의 값을 리턴해보자
print(a[:, ~np.isnan(a).any(axis=0)])  # a[행, 열]

print(a[:, ~np.isnan(a).all(axis=0)])

[False  True  True False]
[ True False False  True]
[[11.  0.]
 [21. 24.]
 [31. 34.]
 [41. 44.]]
[[11.  0. nan  0.]
 [21. nan nan 24.]
 [31.  0. nan 34.]
 [41. 42. 43. 44.]]


* 6. 정렬
numpy.sort() : 정렬 후 ndarray로 리턴
ndarray.sort() : ndarray 자체 정렬
numpy.argsort() : 정렬된 인덱스의 배열을 ndarray로 리턴

In [25]:
# 일차원 배열을 정렬해보자
a = np.array([3,5,2,7,8])
print(a)

a_sort = np.sort(a)
print(a_sort, a)

a_sort_reverse = np.sort(a)[::-1]   # reverse라는 메소드가 없어서 정렬후 역순으로 슬라이싱을 한 후 리턴
print(a_sort_reverse)

[3 5 2 7 8]
[2 3 5 7 8] [3 5 2 7 8]
[8 7 5 3 2]


In [37]:
# 다차원 배열을 정렬해보자
a_2d = np.array([[20,3,100],[1,200,30],[300,10,2]])
print(a_2d)

a_2d_sort = np.sort(a_2d, axis=0)   # axis=0 :열, axis=1 : 행
print(a_2d_sort)

a_2d_sort = np.sort(a_2d, axis=1)   # axis=0 :열, axis=1 : 행
print(a_2d_sort)

a_2d_sort = np.sort(a_2d, axis=-1)   # axis=-1 : 마지막 축에 따라서 정렬된다. [행, 열]
print(a_2d_sort,"\n")

print("   내림차순   ")
a_2d_sort = np.sort(a_2d, axis=0)[::-1]   # axis=0 :열, axis=1 : 행
print(a_2d_sort)

a_2d_sort = np.sort(a_2d, axis=1)[:, ::-1]   # axis=0 :열, axis=1 : 행
print(a_2d_sort)

a_2d_sort = np.sort(a_2d, axis=-1)[:, ::-1]   # axis=-1 : 마지막 축에 따라서 정렬된다. [행, 열]
print(a_2d_sort)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[[  1   3   2]
 [ 20  10  30]
 [300 200 100]]
[[  3  20 100]
 [  1  30 200]
 [  2  10 300]]
[[  3  20 100]
 [  1  30 200]
 [  2  10 300]] 

   내림차순   
[[300 200 100]
 [ 20  10  30]
 [  1   3   2]]
[[100  20   3]
 [200  30   1]
 [300  10   2]]
[[100  20   3]
 [200  30   1]
 [300  10   2]]


In [42]:
# ndarray.sort() : ndarray 자체 정렬
a = np.array([3,5,2,7,8])
print(a)

a.sort()
print(a)

a_2d.sort(axis=0)
print(a_2d)

print(a_2d[::-1])

[3 5 2 7 8]
[2 3 5 7 8]
[[  1   3   2]
 [ 20  10  30]
 [300 200 100]]
[[300 200 100]
 [ 20  10  30]
 [  1   3   2]]


In [44]:
# numpy.argsort() : 정렬된 인덱스의 배열을 ndarray로 리턴
a_2d = np.array([[20,3,100],[1,200,30],[300,10,2]])
print(a_2d)

a_2d_sort_col_index = np.argsort(a_2d, axis=0)
print(a_2d_sort_col_index)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[[1 0 2]
 [0 2 1]
 [2 1 0]]


In [48]:
# numpy.argsort() : 정렬된 인덱스의 배열을 ndarray로 리턴
a_2d = np.array([[20,3,100],[1,200,30],[300,10,2]])
print(a_2d)

# 특정열을 기준으로 정렬
col_num = 1
print(a_2d[:, col_num])  # [3 200 10]
print(np.argsort(a_2d[:, col_num]))  # 1열을 기준으로 정렬한 인덱스

res = a_2d[np.argsort(a_2d[:, col_num])]  # 1열을 기준으로 정렬한 인덱스를 바탕으로 행을 정렬
print(res)

print("   내림차순   ")
print(np.argsort(a_2d[:, col_num])[::-1])

res = a_2d[np.argsort(a_2d[:, col_num])[::-1]]
print(res)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[  3 200  10]
[0 2 1]
[[ 20   3 100]
 [300  10   2]
 [  1 200  30]]
   내림차순   
[1 2 0]
[[  1 200  30]
 [300  10   2]
 [ 20   3 100]]


In [53]:
# 특정행을 기준으로 정렬 하고 싶다.
row_num = 1
print(a_2d[row_num])

# 정렬 후 인덱스를 리턴 받고 싶다.
print(np.argsort(a_2d[row_num]))  # 1행의 정렬 인덱스를 리턴

a_2d_sort_row_num = a_2d[:,np.argsort(a_2d[row_num])]
print(a_2d_sort_row_num)

[  1 200  30]
[0 2 1]
[[ 20 100   3]
 [  1  30 200]
 [300   2  10]]


* 6. 계산
1) 행과 열의 집계 함수 : 합계_sum, 평균_mean, 최대, 최소 / clip, 표준편차_std, 분산_var
2) 표준화 목록(list, Numpy 배열을 pandas.DataFrame) -> 정규화 패턴
    >> 정규화 종류 / 표준화 Scipy, scikit-learn /
    >> list(표준화, 규격화), Numpy.ndarray, pandas.DataFrame
3) ndarray의 최대, 최소 인덱스를 리턴
4) one - hot : eye(), indentity()
5) ndarray 이동시키는 작업
6) 매트릭스 연산(행렬, 역행렬)

In [57]:
# 1) 행과 열의 집계 함수 : 합계_sum, 평균_mean, 최대, 최소 /clip, 표준편차_std, 분산_var
a = np.arange(12).reshape(3,4)
print(a)

print(np.sum(a))

print(np.sum(a, axis=0))  # 열의 합계
print(np.sum(a, axis=1))  # 행의 합계

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [62]:
# np.clip(), ndarray.clip() : 배열 요소의 값을 임의의 간격에 맞추어 처리
# 인수로, 최소값, 최대값을 지정하게 되면 해당 범위에서 벗어나면 최소값, 최대값으로 대체된다.
# 0.0 ~ 1.0 / 0 ~ 255
a = np.arange(10)
print(a)

# np.clip()
print(np.clip(a,2,7))  # 최소 2, 최대 7  : 매개인수가 필수로 3개 지정
print(np.clip(a,None,7))  # 최소값, 최대 7
print('----------------------------------')

# ndarray.clip()
print(a.clip(2))
print(a.clip(min=2))
print(a.clip(max=8))

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 7 7]
[0 1 2 3 4 5 6 7 7 7]
----------------------------------
[2 2 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 8]


In [65]:
# 3) ndarray의 최대, 최소 인덱스를 리턴
ar = np.array([1,100,10])
print(ar,"\n")

print(np.argmax(ar),"\n")
print(np.argmin(ar),"\n")

[  1 100  10] 

1 

0 



In [76]:
# unravel_index(indices, shape, order='C')
a_2d = np.array([[20,50,30],[60,100,10]])
print(a_2d,"\n")
print(np.argmax(a_2d),"\n")  # 일차원으로 나열해서 해당 인덱스 값을 리턴한다.

idx = np.unravel_index(np.argmax(a_2d), a_2d.shape)
print(idx, a_2d[idx],"\n")

print("np.where()로 리턴을 받아보자")
print(np.where(a_2d == np.max(a_2d)),"\n")

print(list(zip(*np.where(a_2d == np.max(a_2d)))),"\n")
print(list(zip(*np.where(a_2d == np.min(a_2d)))),"\n")

[[ 20  50  30]
 [ 60 100  10]] 

4 

(1, 1) 100 

np.where()로 리턴을 받아보자
(array([1], dtype=int64), array([1], dtype=int64)) 

[(1, 1)] 

[(1, 2)] 



In [84]:
# 5) ndarray 이동시키는 작업  np.roll(a, shift, axis=None)
a = np.arange(10)
print(a, '\n')

a_roll = np.roll(a,3)
print(a_roll, '\n')

# 다차원 배열 이동
a_2d = np.arange(12).reshape(3,4)
print(a_2d, '\n')
print(np.roll(a_2d, 2), '\n')

# 열을 1나 오른쪽으로 이동
print(np.roll(a_2d, 1, axis=0), '\n')

print(np.roll(a_2d, (1,2)), '\n')

[0 1 2 3 4 5 6 7 8 9] 

[7 8 9 0 1 2 3 4 5 6] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[10 11  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]] 

[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]] 

[[ 9 10 11  0]
 [ 1  2  3  4]
 [ 5  6  7  8]] 



6) 매트릭스 연산(행렬, 역행렬)
- 행렬 객체 생성 : numpy.array(), numpy.matrix()
- 전치 행렬 : .T  -> 행과 열을 바꾸는 것
- 행렬의 합, 차 : +, -
- 요소의 곱 : *, numpy.multiply()
- 행렬의 곱 : numpy.dot(), numpy.matmul(), @연산자, `*연산자`
- 거듭제곱 : `**`
- 벡터의 내적 : numpy.inner()
- 역행렬 : numpy.linalg.inv(), `**-1`, .I(대문자 i)속성
- 행렬식 : numpy.linalg.det()
- 고유치, 고유벡터 : numpy.linalg.eig()

In [102]:
# 행렬 객체 생성 : numpy.matrix()
mat = np.matrix([1,2,3,4,5,6])
print(mat.shape, '\n')
print('========================================')

# 전치 행렬 : .T  -> 행과 열을 바꾸는 것
ar = np.arange(6).reshape(2,3)
print(ar)
print(ar.T, '\n')
print('========================================')

# 행렬의 합, 차 : +, -
ar02 = np.arange(0,12,2).reshape(2,3)
print(ar02, '\n')

print('------- + ------')
print(ar + ar02,'\n')

m01 = np.matrix(ar)
m02 = np.matrix(ar02)

print(m01 + m02, '\n')

# 요소의 곱 : *, numpy.multiply()
print('------- * ------')
print(ar * ar02,'\n')
print(np.multiply(m01, m02), '\n')

# 행렬의 곱 : numpy.dot(), numpy.matmul(), @연산자, `*연산자`  ver 3.5이상
print('========================================')
ar01 = np.arange(4).reshape(2,2)
print(ar01, '\n')
ar02 = np.arange(6).reshape(2,3)
print(ar02, '\n')

print(np.dot(ar01, ar02), '\n')
print(ar01 @ ar02, '\n')

(1, 6) 

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]] 

[[ 0  2  4]
 [ 6  8 10]] 

------- + ------
[[ 0  3  6]
 [ 9 12 15]] 

[[ 0  3  6]
 [ 9 12 15]] 

------- * ------
[[ 0  2  8]
 [18 32 50]] 

[[ 0  2  8]
 [18 32 50]] 

[[0 1]
 [2 3]] 

[[0 1 2]
 [3 4 5]] 

[[ 3  4  5]
 [ 9 14 19]] 

[[ 3  4  5]
 [ 9 14 19]] 



* 7. 파일의 입출력
1) csv 파일을 읽기 : np.loadtxt()
loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    가로와 세로를 지정해서 읽어온다. : skiprows, usecols
    
2) 복잡한 파일을 로드 : np.genfromtxt()
    - 결측값 처리
    - 다른데이터 형식 처리

3) .cvs 파일 출력 : np.savetxt()
savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    - 출력 포맷 : fmt
    - 출력 할 수 있는 차원 : -X : 1D or 2D array_like

4) pandas를 읽고 쓰기  --------------------> 헤더가 포함되고 숫자 문자가 혼합된 파일
    - 머리글 행, 열이 있는 csv 파일 처리
    - 결손치 처리
    - 다른형태의 데이터 형식 처리
    
------> ! ndarray를 이진 파일로 저장(npy, npz)

In [113]:
# 1. 파이썬으로 파일을 로드
with open('sample.csv') as f:
    print(f.read())
    
with open('sample02.csv') as f:
    print(f.read())

11,12,100,120
21,22,23,24
31,49,82,34
41,42,43,44

a,b,c,d
one,11,12,100,120
two,21,11,11,24
three,31,11,23,34


In [118]:
# 2. np.loadtxt()를 이용해서 파일을 로드
a = np.loadtxt('sample.csv', delimiter=',', dtype='int64')  # ndarray로 반환(배열)
print(a)
print(type(a), a.dtype, a.shape, '\n')
print('=========================================')

# 2. np.loadtxt()를 이용해서 파일을 로드 문자열을 제외한 숫자인 데이터만 읽어오고 싶다.
a = np.loadtxt('sample02.csv', delimiter=',', skiprows=1, usecols=[1,2,3,4])  # ndarray로 반환(배열)
print(a)
print(type(a), a.dtype, a.shape, '\n')
print('=========================================')

# 2. np.loadtxt()를 이용해서 다른형식이 문자 숫자 혼형으로 들어온 파일처리
my_type = {'names': ('no', 'a', 'b', 'c', 'd'),'formats': ('<U5', 'i4', 'i4', 'i4', 'i4')}

a = np.loadtxt('sample02.csv', dtype=my_type, delimiter=',', skiprows=1)  # ndarray로 반환(배열)
print(a)
print(type(a), a.dtype, a.shape, '\n')

[[ 11  12 100 120]
 [ 21  22  23  24]
 [ 31  49  82  34]
 [ 41  42  43  44]]
<class 'numpy.ndarray'> int64 (4, 4) 

[[ 11.  12. 100. 120.]
 [ 21.  11.  11.  24.]
 [ 31.  11.  23.  34.]]
<class 'numpy.ndarray'> float64 (3, 4) 

[('one', 11, 12, 100, 120) ('two', 21, 11,  11,  24)
 ('three', 31, 11,  23,  34)]
<class 'numpy.ndarray'> [('no', '<U5'), ('a', '<i4'), ('b', '<i4'), ('c', '<i4'), ('d', '<i4')] (3,) 



In [112]:
# ex)
from io import StringIO
d = StringIO("M 21 72\nF 35 58")
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21, 72.), (b'F', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [130]:
# 3) .cvs 파일 출력 : np.savetxt()
a = np.arange(6).reshape(2,3)
np.savetxt('sample03.csv', a*2, fmt='%3d', delimiter=',')  # %.2f, %.5e

with open('sample03.csv') as f:
    print(f.read())

           
a = np.arange(6).reshape(2,3)
np.savetxt('sample03.tsv', a*2, fmt='%3d', delimiter='\t')  # %.2f, %.5e

with open('sample03.tsv') as f:
    print(f.read())

  0,  2,  4
  6,  8, 10

  0	  2	  4
  6	  8	 10



9. 이미지 처리 : Pillow, Numpy, OpenCV ....
영상, 이미지 -> Numpy : ndarray
영상, 이미지 -> OpenCV -> Numpy : ndarray
영상, 이미지 -> Pillow + Numpy

Pillow(PIL) : 이미지 처리 라이브러리 -> 크기조정, 자르기 등의 기본 작업
Numpy + (Pillow(PIL) | OpenCV) : 과학계산 라이브러리 -> 화소 값 대한 산술연산, 대용량 이미지, 영상 등을 일괄로 로드
OpenCV : 컴퓨터 비전 라이브러리 -> 얼굴인식 등의 CV가 원하는 시스템의 동작을 원하는 경우