!jupyter nbconvert --to script day01.ipynb -> py로 변환하는 명령어

1. 기본정보(버전확인, 데이터 형식, 목록, 형변환, python list와 numpy.ndarray의 차이점)
2. 표시설정(numpy.ndarray 설정값, 배열의 초기화 및 생성 _행렬만들기, 난수 배열값 채우기, 대각선)
3. 배열의 행, 열, 추출, 추가, 삭제, 결합, 분할
4. 조건처리
5. 결측값 처리
6. 정렬
7. 파일의 입출력
8. 다른 형식으로 값 변환
9. 이미지 처리

In [1]:
import numpy as np

In [2]:
# 버전확인

print(np.__version__)
print(np.version.full_version)
print(np.version.release)
print(np.version.git_revision)

1.19.2
1.19.2
True
68752f786df542d340f25c41a8920d9b2aed66cf


In [22]:
a = np.array([1,2,3])  # 1차원
print(a) 


a2 = np.array([[1,2,3], [4,5,6]])
a2

a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a3.size

a4 = np.arange(6)
a4.reshape(2,3)


[1 2 3]


array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
# 1. 기본정보(데이터 형식)

ar = [1,2,3,4,5]
print(ar, type(ar))

# ndarray는 데이터형식 dtype, np.array()를 통해서 ndarray 객체를 생성한다.

a = np.array([1,2,3], dtype=np.int64)  # dytpe으로 지정
print(type(a))
print(a)
print(a.dtype)

a = np.array([1,2,3], dtype='int64')  # ''안에 문자값으로 타입을 지정
print(a)
print(a.dtype)

a = np.array([1,2,3], dtype='i8')  # 형태 코드 문자열로 타입을 지정
print(a)
print(a.dtype)

# 숫자범위를 정수 및 실수의 최소값 최대값을 확인
# int, uint 정수 범위 np.iinfo()

r = np.iinfo(np.int64)
print(type(r))
print(r, r.min, r.max)
print(r.min + 10)

print(np.iinfo('i4'))
print(np.iinfo(int))

# float np.finfo()
fi64 = np.finfo(np.float64)
print(type(fi64))
print(fi64)

# 문자열로 변환 정보
a_str = np.array([1,2,3], dtype=str)
print(a_str)
print(a_str.dtype)

a_str[0] = 'abcde'
print(a_str)

a_str = np.array([1,2,3], dtype='U10')
print(a_str)
print(a_str.dtype)

a_str[0] = 'abcde'
print(a_str)


[1, 2, 3, 4, 5] <class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
int64
[1 2 3]
int64
[1 2 3]
int64
<class 'numpy.iinfo'>
Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------
 -9223372036854775808 9223372036854775807
-9223372036854775798
Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

<class 'numpy.finfo'>
Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-

In [19]:
# object
res_obj = np.array([1,0.1,'abcd'], dtype=object)
print(res_obj)

print(res_obj.dtype)

print(type(res_obj[0]))
print(type(res_obj[1]))
print(type(res_obj[2]))

print(res_obj*2)

[1 0.1 'abcd']
object
<class 'int'>
<class 'float'>
<class 'str'>
[2 0.2 'abcdabcd']


In [21]:
# astype() 메소드를 통해서 ndarray 객체로 변환해서 사용 할 수 있다.

ar = np.array([1,2,3])
print(ar, ar.dtype)

ar_float = ar.astype(np.float32)
print(ar_float)
print(ar_float.dtype)

ar_float = ar.astype(float)
print(ar_float)
print(ar_float.dtype)

ar_str = ar.astype('str')
print(ar_str)
print(ar_str.dtype)

# float -> int 소수이하 버림 음수값이 0으로 반올림된다.
# np.round()를 사용해서 반올림 확인

print(np.round(0.5).astype(int))

[1 2 3] int32
[1. 2. 3.]
float32
[1. 2. 3.]
float64
['1' '2' '3']
<U11
0


In [23]:
# python list와 numpy.ndarray의 차이점
# 목록 : list
# 배열 : array
# 다차원 배열 : numpy.ndarray

# 목록
my_list = ['apple', 100, 10.2]
print(my_list)
print(my_list[:2])

list_2d = [1,2,3,[4,5,6],[7,8,9]]
print(list_2d)

# max(), min(), sum(), len()
my_list02 = [0,1,10,20,30]
print(my_list02)
print(max(my_list02))
print(min(my_list02))
print(sum(my_list02))
print(len(my_list02))

# for (range, enumerate, zip)
# list 요소 추가시 : append, extend, insert
# 제거 : clear, pop, remove, del

['apple', 100, 10.2]
['apple', 100]
[1, 2, 3, [4, 5, 6], [7, 8, 9]]
[0, 1, 10, 20, 30]
30
0
61
5


In [33]:
# 배열
import array 
ar = array.array('i',[1,2,3])
print(ar)
ar = array.array('f',[1,2,3])
print(ar[0])

array('i', [1, 2, 3])
1.0


In [40]:
# 2. 표시설정(numpy.ndarray 설정값 배열이 초기화 및 생성 _행렬만들기, 난수 배열값 채우기, 대각선)
print(np.get_printoptions())
a = np.array([12.123456, 0.123456789])
print(a)

np.set_printoptions(precision = 10)
print(a)

np.set_printoptions(precision = 10, floatmode = 'fixed')
print(a)

np.set_printoptions(precision = 10, formatter = {'float' : '{:.2f}'.format})
print(a)

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'fixed', 'precision': 10, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': {'float': <built-in method format of str object at 0x00000252DE174FB0>}, 'legacy': False}
[12.12 0.12]
[12.1234560000  0.1234567890]
[12.1234560000  0.1234567890]
[12.12 0.12]
[  12 1234]


In [46]:
# 배열의 데이터를 2진, 8진, 16진수로 출력만 해보자
ar = np.array([12, 1234])
print(ar)

np.set_printoptions(precision = 10, formatter = {'int' : '{:08d}'.format})
print(ar)

np.set_printoptions(precision = 10, formatter = {'int' : '{:b}'.format})
print(ar)

np.set_printoptions(precision = 10, formatter = {'int' : '{:o}'.format})
print(ar)

np.set_printoptions(precision = 10, formatter = {'int' : '{:x}'.format})
print(ar)

ar02 = np.array(['One', 'Two'])
print(ar02)

np.set_printoptions(formatter = {'numpystr' : str.upper})
print(ar02)

np.set_printoptions(formatter = {'numpystr' : lambda x : 'xxx' + x + '====='})
print(ar02)

[c 4d2]
[00000012 00001234]
[1100 10011010010]
[14 2322]
[c 4d2]
['One' 'Two']
[ONE TWO]
[xxxOne===== xxxTwo=====]


배열의 초기화 및 생성 행렬만들기, 난수 배열값 채우기, 대각선
  1. 차원의 수 : ndim
  2. 차원의 크기 : shape
  3. 전체 요소의 수 : size
  4. 다차원의 첫번째 차원의 길이 : len()

In [52]:
a_1d = np.arange(3)
print(a_1d)

a_2d = np.arange(12).reshape((3,4))  # 2차원
print(a_2d)
print(a_2d.ndim)  # 차원수확인

a_3d = np.arange(24).reshape((2,3,4))  # 3차원
print(a_3d)
print(a_3d.ndim, a_3d.shape, a_3d.size)  # 차원수확인, 차원확인, 개수확인

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3 (2, 3, 4) 24
